### ISSUE TITLE
Use lighter blue for <a> elements as to improve the visibility of links

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/interface_guidelines#2]
Currently links (from an <a> html element) are shown in #07426e - it is too difficult to distinguish this colour from the standard body text colour (#333). Changing the link colour to #0080AA solves this issue.

See screenshots in the attachment for an impression.
![link-dark-blue](https://cloud.githubusercontent.com/assets/8073487/17096348/25f53f30-5259-11e6-9e3d-68fc9dda7482.png)
![link-light-blue](https://cloud.githubusercontent.com/assets/8073487/17096349/25fa8a6c-5259-11e6-9442-442441f90349.png)

**Comment by twagoo** [comment]
See https://github.com/clarin-eric/base_style/issues/1
